# https://taskfile.dev

version: '3'
tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the binary
    cmds:
      - uvx cosmofy bundle

  install:
    desc: Install globally with uv
    cmds:
      - uv tool install .

  uninstall:
    desc: Uninstall the global install
    cmds:
      - uv tool uninstall parallel-rsync
